// This file is automatically generated. Any changes will be overwritten.

#ifndef INTERFACE_HPP
#define INTERFACE_HPP

#include <ArduinoJson.h>

#define JSON_DOC_SIZE_RX 61
#define JSON_DOC_SIZE_TX 88

struct ReceiveInterface {
bool calibrate;
bool control_state;
double pos_setpoint;

void from_doc(StaticJsonDocument<JSON_DOC_SIZE_RX> &doc);
};

struct TransmitInterface {
struct {
double pos_rad;
double pos_deriv_rad_s;
} wheel;
struct {
struct {
double from_pitch;
double from_acc;
} angle_deg;
struct {
double from_pitch;
double from_acc;
} angle_deriv_deg_s;
double vel_deg_s;
} tilt;

void to_doc(StaticJsonDocument<JSON_DOC_SIZE_TX> &doc);
};

#endif
